### ISSUE TITLE
rspec dont run on Ruby 2.1.0

### ISSUE THREAD

**Issue by filipiz** [puppetlabs/puppetlabs-mysql#433]
Hi guys.

I couldn't run the tests on Ruby 2.1.0
The stacktrace is bellow.
Maybe can be important to the project make the environment updated.
Have no idea of the priority of this or even if it is necessary.
Please, just close the ticket if you consider this not important.

With 1.9.3 it works smoothly.

``` shell
➜  puppetlabs-mysql git:(master) ✗ be rspec spec
/Users/filipi/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/puppet-3.4.2/lib/puppet/util/autoload.rb:68:in `rescue in load_file': Could not autoload puppet/type/component: can't modify frozen Symbol (Puppet::Error)
    from /Users/filipi/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/puppet-3.4.2/lib/puppet/util/autoload.rb:59:in `load_file'
    from /Users/filipi/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/puppet-3.4.2/lib/puppet/util/autoload.rb:200:in `load'
    from /Users/filipi/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/puppet-3.4.2/lib/puppet/metatype/manager.rb:159:in `type'
    from /Users/filipi/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/puppet-3.4.2/lib/puppet/type.rb:2466:in `<top (required)>'
    from /Users/filipi/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/puppet-3.4.2/lib/puppet.rb:175:in `require'
    from /Users/filipi/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/puppet-3.4.2/lib/puppet.rb:175:in `<top (required)>'
    from /Users/filipi/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/rspec-puppet-1.0.1/lib/rspec-puppet.rb:1:in `require'
    from /Users/filipi/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/rspec-puppet-1.0.1/lib/rspec-puppet.rb:1:in `<top (required)>'
    from /Users/filipi/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/puppetlabs_spec_helper-0.4.1/lib/puppetlabs_spec_helper/module_spec_helper.rb:1:in `require'
    from /Users/filipi/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/puppetlabs_spec_helper-0.4.1/lib/puppetlabs_spec_helper/module_spec_helper.rb:1:in `<top (required)>'
    from /Users/filipi/nextt/lib-repositories/puppetlabs-mysql/spec/spec_helper.rb:5:in `require'
    from /Users/filipi/nextt/lib-repositories/puppetlabs-mysql/spec/spec_helper.rb:5:in `<top (required)>'
    from /Users/filipi/nextt/lib-repositories/puppetlabs-mysql/spec/classes/mysql_bindings_spec.rb:1:in `require'
    from /Users/filipi/nextt/lib-repositories/puppetlabs-mysql/spec/classes/mysql_bindings_spec.rb:1:in `<top (required)>'
    from /Users/filipi/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/rspec-core-2.14.7/lib/rspec/core/configuration.rb:896:in `load'
    from /Users/filipi/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/rspec-core-2.14.7/lib/rspec/core/configuration.rb:896:in `block in load_spec_files'
    from /Users/filipi/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/rspec-core-2.14.7/lib/rspec/core/configuration.rb:896:in `each'
    from /Users/filipi/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/rspec-core-2.14.7/lib/rspec/core/configuration.rb:896:in `load_spec_files'
    from /Users/filipi/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/rspec-core-2.14.7/lib/rspec/core/command_line.rb:22:in `run'
    from /Users/filipi/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/rspec-core-2.14.7/lib/rspec/core/runner.rb:80:in `run'
    from /Users/filipi/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/rspec-core-2.14.7/lib/rspec/core/runner.rb:17:in `block in autorun'
/Users/filipi/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/puppet-3.4.2/lib/puppet/util/monkey_patches.rb:78:in `to_proc': can't modify frozen Symbol (RuntimeError)
    from /Users/filipi/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/simplecov-0.8.2/lib/simplecov/result.rb:30:in `initialize'
    from /Users/filipi/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/simplecov-0.8.2/lib/simplecov.rb:44:in `new'
    from /Users/filipi/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/simplecov-0.8.2/lib/simplecov.rb:44:in `result'
    from /Users/filipi/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/simplecov-0.8.2/lib/simplecov/configuration.rb:139:in `block in at_exit'
    from /Users/filipi/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/simplecov-0.8.2/lib/simplecov/defaults.rb:54:in `call'
    from /Users/filipi/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/simplecov-0.8.2/lib/simplecov/defaults.rb:54:in `block in <top (required)>'
```

**Comment by Aaron-Rob** [comment]
Hello! We are doing some house keeping and noticed that this issue has been open for a long time. We're going to close it but please do raise another issue if the issue still persists. :smile:
